
#include "hal.h"

void init(void)
{
  AFIO->MAPR |= AFIO_MAPR_SWJ_CFG_JTAGDISABLE;

  AFIO->MAPR |= AFIO_MAPR_TIM1_REMAP_NOREMAP;
  AFIO->MAPR |= AFIO_MAPR_TIM2_REMAP_NOREMAP;
  AFIO->MAPR |= AFIO_MAPR_TIM3_REMAP_PARTIALREMAP;
  //AFIO->MAPR |= AFIO_MAPR_TIM4_REMAP;

  AFIO->MAPR |= AFIO_MAPR_USART3_REMAP_NOREMAP;
  AFIO->MAPR |= AFIO_MAPR_USART1_REMAP;
}
